#! /bin/sh

dex -ae bspwm
dex /etc/xdg/autostart/xfsettingsd.desktop
dex /etc/xdg/autostart/xfce4-notifyd.desktop
picom --experimental-backends

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config borderless_monocle   true
bspc config gapless_monocle      true
